name: new-hybrid
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - opencv
  - pillow
  - py-opencv
  - pyparsing
  - python=3.12
  - pyttk
  - scipy
  - tk


